package fr.piotr.reactions.registry;

/**
 * Created by piotr_000 on 20/11/2016.
 *
 */

public interface AppActions {

//    String ACTION_ADD_REACTION = "ACTION_ADD_REACTION";
//    String EXTRA_FLAT_RULE = "EXTRA_FLAT_RULE";
//    String ACTION_REMOVE_REACTION = "ACTION_REMOVE_REACTION";

    String ACTION_REGISTER_LIGHT_SENSOR = "ACTION_REGISTER_LIGHT_SENSOR";
    String ACTION_UNREGISTER_LIGHT_SENSOR = "ACTION_UNREGISTER_LIGHT_SENSOR";
    String EXTRA_SENSOR = "EXTRA_SENSOR";

    String EXTRA_EVENT_ID = "EXTRA_EVENT_ID";
//    String EXTRA_REACTION_ID = "EXTRA_REACTION_ID";

}
